input CreateUserInput {
  address: String!
  email: String!
  name: String!
  password: String!
  phone: String!
}

type Mutation {
  createUser(createUserInput: CreateUserInput!): User!
  login(email: String!, password: String!): String!
  removeUser(_id: String!): User!
  updateUser(updateUserInput: UpdateUserInput!): User!
}

type Query {
  currentUser: User!
  getHello: String!
  user(_id: String!): User!
  users: [User!]!
}

input UpdateUserInput {
  _id: String!
  address: String
  email: String
  name: String
  password: String
  phone: String
}

type User {
  _id: ID!
  address: String!
  email: String!
  name: String!
  password: String!
  phone: String!
}